#include "cadr_m4_media.h"
#include "cadr_state_v2.h"
#include "cadr_state_v3.h"
#include "cadr_state_v4.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static int failures;
#define CHECK(x) do { if(!(x)){(void)fprintf(stderr,"FAIL %s:%d: %s\n",__FILE__,__LINE__,#x);failures++;} } while(0)
static void p32(uint8_t*p,uint32_t v){p[0]=(uint8_t)v;p[1]=(uint8_t)(v>>8U);p[2]=(uint8_t)(v>>16U);p[3]=(uint8_t)(v>>24U);} static void p64(uint8_t*p,uint64_t v){uint32_t i;for(i=0U;i<8U;++i)p[i]=(uint8_t)(v>>(i*8U));}
static cadr_machine_state *state(void){cadr_machine_state*s=calloc(1U,sizeof(*s));if(s==NULL)return NULL;s->memory.main_memory_pages=1U;s->memory.mapped_words=CADR_MAIN_MEMORY_WORDS_PER_PAGE;s->canonical.initialized=1U;s->canonical.mutation_count=1U;s->canonical.mutation_events[0][0]=0x31U;s->events.generation=17U;s->events.next_request_id=4U;if(cadr_state_v2_rebuild(s)!=CADR_STATUS_OK){free(s);return NULL;}return s;}
static void free_state(cadr_machine_state*s){if(s!=NULL){free(s->events.completion_bytes);free(s);}}
static void request(cadr_m4_media_turn*t,uint64_t ordinal,uint32_t actor,const uint8_t payload[1024]){(void)memset(t,0,sizeof(*t));t->ordinal=ordinal;t->actor=actor;t->operation=CADR_HOST_OPERATION_BLOCK_WRITE;t->actor_status=CADR_STATUS_OK;t->guest_tick=100U+ordinal;t->generation=17U;t->request_id=3U;t->descriptor_byte_count=24U;t->request_payload_byte_count=1024U;p64(t->descriptor,3U);p64(t->descriptor+8U,1U);p32(t->descriptor+16U,1U);p32(t->descriptor+20U,1024U);cadr_m4_media_sha256(t->descriptor,24U,t->descriptor_sha256);cadr_m4_media_sha256(payload,1024U,t->request_payload_sha256);(void)memcpy(t->page_sha256,t->request_payload_sha256,32U);}
static void test_state_vector(void){static const uint8_t golden[32]={0x5f,0x8b,0xa7,0xa2,0xcd,0xb3,0x4d,0xc9,0x40,0x16,0x18,0xb6,0x84,0xd0,0x10,0x42,0xe5,0x2d,0x40,0xc5,0xb7,0x6a,0x77,0xce,0x9a,0x3c,0x0c,0x8a,0x6f,0x29,0x5c,0xd0};cadr_machine_state*s=state();uint8_t v3a[32],v3b[32],v4a[32],v4b[32];if(s==NULL){CHECK(0);return;}s->events.outstanding_request_id=3U;s->events.outstanding_operation=CADR_HOST_OPERATION_BLOCK_WRITE;s->events.request_descriptor_byte_count=24U;s->events.request_payload_byte_count=1024U;p64(s->events.request_descriptor,3U);p64(s->events.request_descriptor+8U,1U);p32(s->events.request_descriptor+16U,1U);p32(s->events.request_descriptor+20U,1024U);(void)memset(s->events.request_payload,0x61U,1024U);CHECK(cadr_state_v3_digest(s,v3a)==CADR_STATUS_OK);CHECK(cadr_state_v4_digest(s,v4a)==CADR_STATUS_OK);CHECK(memcmp(v4a,golden,32U)==0);s->events.request_payload[7]^=1U;CHECK(cadr_state_v3_digest(s,v3b)==CADR_STATUS_OK);CHECK(cadr_state_v4_digest(s,v4b)==CADR_STATUS_OK);CHECK(memcmp(v3a,v3b,32U)==0);CHECK(memcmp(v4a,v4b,32U)!=0);s->events.completion_queued=2U;CHECK(cadr_state_v4_digest(s,v4b)==CADR_STATUS_INVALID_ARGUMENT);free_state(s);}
static void test_media_vector_and_rejections(void){static const uint8_t golden[32]={0x84,0x51,0x55,0xde,0xe9,0x46,0x70,0xc7,0xe0,0x99,0x94,0xac,0x60,0x55,0xa9,0xe5,0x65,0x01,0x36,0xfd,0xff,0xd1,0x63,0xc1,0xa1,0x36,0x0f,0x54,0x69,0x05,0x8f,0x17};cadr_m4_media_header h;cadr_m4_media_turn t[5];cadr_machine_state*s=state();uint8_t payload[1024],root[32],blob[64U+5U*352U],copy[sizeof(blob)],digest[32];cadr_m4_media_difference d;uint64_t written;uint32_t i;if(s==NULL){CHECK(0);return;}for(i=0U;i<1024U;++i)payload[i]=(uint8_t)i;cadr_m4_media_selected_base(&h);request(&t[0],0U,CADR_M4_MEDIA_ACTOR_ISSUE,payload);CHECK(cadr_m4_media_overlay_root(&h,t,0U,root)==CADR_STATUS_OK);(void)memcpy(t[0].overlay_root_sha256,root,32U);request(&t[1],1U,CADR_M4_MEDIA_ACTOR_CAPTURE,payload);(void)memcpy(t[1].overlay_root_sha256,root,32U);request(&t[2],2U,CADR_M4_MEDIA_ACTOR_DELIVERY,payload);t[2].disposition=CADR_M4_MEDIA_DISPOSITION_COMMIT;CHECK(cadr_m4_media_overlay_root(&h,t,3U,root)==CADR_STATUS_OK);t[2].overlay_generation=1U;(void)memcpy(t[2].overlay_root_sha256,root,32U);request(&t[3],3U,CADR_M4_MEDIA_ACTOR_APPLY,payload);t[3].disposition=CADR_M4_MEDIA_DISPOSITION_COMMIT;t[3].overlay_generation=1U;(void)memcpy(t[3].overlay_root_sha256,root,32U);CHECK(cadr_m4_media_build_stable_turn(s,4U,104U,1U,root,&t[4])==CADR_STATUS_OK);CHECK(cadr_m4_media_serialize(&h,t,5U,blob,sizeof(blob),&written)==CADR_STATUS_OK);cadr_m4_media_sha256(blob,written,digest);CHECK(memcmp(digest,golden,32U)==0);(void)memcpy(copy,blob,sizeof(copy));CHECK(cadr_m4_media_compare(blob,sizeof(blob),copy,sizeof(copy),&d)==CADR_STATUS_OK);copy[64U+2U*352U+248U]^=1U;CHECK(cadr_m4_media_compare(blob,sizeof(blob),copy,sizeof(copy),&d)!=CADR_STATUS_OK);(void)memcpy(copy,blob,sizeof(copy));copy[64U+1U*352U+176U]^=1U;CHECK(cadr_m4_media_compare(blob,sizeof(blob),copy,sizeof(copy),&d)!=CADR_STATUS_OK);h.base_byte_count-=1U;written=UINT64_MAX;CHECK(cadr_m4_media_serialize(&h,t,5U,copy,sizeof(copy),&written)==CADR_STATUS_INVALID_ARGUMENT);CHECK(written==0U);free_state(s);}
int main(void){test_state_vector();test_media_vector_and_rejections();if(failures!=0)return 1;(void)puts("cadr state v4/media tests passed");return 0;}
