#include "cadr_disk_evidence.h"
#include "cadr_m4_media.h"
#include <string.h>
static void p32(uint8_t*p,uint32_t v){p[0]=(uint8_t)v;p[1]=(uint8_t)(v>>8U);p[2]=(uint8_t)(v>>16U);p[3]=(uint8_t)(v>>24U);}static void p64(uint8_t*p,uint64_t v){uint32_t i;for(i=0U;i<8U;++i)p[i]=(uint8_t)(v>>(i*8U));}
void cadr_disk_evidence_reset(cadr_disk_evidence_log*l){if(l!=NULL)(void)memset(l,0,sizeof(*l));}
void cadr_disk_evidence_observe(cadr_disk_evidence_log*l,uint64_t slot,const cadr_disk_evidence_tuple*a){if(l==NULL||a==NULL)return;l->observed_before=l->have_last!=0U?l->last_after:*a;l->observed_after=*a;if(l->have_last==0U||slot!=l->last_slot){l->last_slot=slot;l->intra_slot=0U;}else l->intra_slot++;}
cadr_status cadr_disk_evidence_record(cadr_disk_evidence_log*l,uint32_t k,uint32_t f,uint64_t first,uint64_t second,uint32_t value,uint32_t detail,const uint8_t*b,uint64_t n){cadr_disk_evidence_event*e;if(l==NULL||k<CADR_DISK_EVIDENCE_REGISTER_READ||k>CADR_DISK_EVIDENCE_INTERRUPT||(n!=0U&&b==NULL))return CADR_STATUS_INVALID_ARGUMENT;if(l->overflowed!=0U||l->count==CADR_DISK_EVIDENCE_CAPACITY){l->overflowed=1U;return CADR_STATUS_GUEST_FAULT;}e=&l->events[l->count++];(void)memset(e,0,sizeof(*e));e->sequence=l->next_sequence++;e->post_slot=l->last_slot;e->intra_slot=l->intra_slot;e->kind=k;e->flags=f;e->first=first;e->second=second;e->value=value;e->detail=detail;e->before=l->observed_before;e->after=l->observed_after;e->delivered_completion=n;cadr_m4_media_sha256(b,n,e->page_sha256);cadr_m4_media_sha256(NULL,0U,e->descriptor_sha256);cadr_m4_media_sha256(NULL,0U,e->payload_sha256);cadr_m4_media_sha256(NULL,0U,e->delivery_sha256);if(k==CADR_DISK_EVIDENCE_BLOCK_REQUEST){e->descriptor_sha256[0]=0U;}if(k==CADR_DISK_EVIDENCE_DELIVERY)(void)memcpy(e->delivery_sha256,e->page_sha256,32U);l->last_after=l->observed_after;l->have_last=1U;return CADR_STATUS_OK;}
cadr_status cadr_disk_evidence_serialized_size(const cadr_disk_evidence_log*l,uint64_t*c){if(l==NULL||c==NULL||l->overflowed!=0U||l->count>CADR_DISK_EVIDENCE_CAPACITY)return CADR_STATUS_NOT_READY;*c=16U+(uint64_t)l->count*384U;return CADR_STATUS_OK;}
static void tuple(uint8_t*p,const cadr_disk_evidence_tuple*t){p64(p,t->lba);p64(p+8U,t->generation);p64(p+16U,t->request_id);p64(p+24U,t->expected_completion);p32(p+32U,t->command);p32(p+36U,t->clp);p32(p+40U,t->da);p32(p+44U,t->lma);p32(p+48U,t->ccw_address);p32(p+52U,t->ccw_index);p32(p+56U,t->status);p32(p+60U,t->transfer_reset_enables);p32(p+64U,t->bus_irq);p32(p+68U,t->operation);p32(p+72U,t->completion_queued);}
cadr_status cadr_disk_evidence_serialize(const cadr_disk_evidence_log*l,uint8_t*b,uint64_t cap,uint64_t*w){uint64_t n,i;cadr_status s;if(w!=NULL)*w=0U;if(l==NULL||b==NULL||w==NULL)return CADR_STATUS_INVALID_ARGUMENT;s=cadr_disk_evidence_serialized_size(l,&n);if(s!=0U)return s;if(cap<n)return CADR_STATUS_WRONG_LENGTH;(void)memset(b,0,(size_t)n);(void)memcpy(b,"CDRDISKEVID1",12U);p32(b+12U,l->count);for(i=0U;i<l->count;++i){const cadr_disk_evidence_event*e=&l->events[i];uint8_t*p=b+16U+i*384U;p64(p,e->sequence);p64(p+8U,e->post_slot);p32(p+16U,e->intra_slot);p32(p+20U,e->kind);p32(p+24U,e->flags);p32(p+28U,e->value);p32(p+32U,e->detail);p64(p+40U,e->first);p64(p+48U,e->second);p64(p+56U,e->delivered_completion);tuple(p+64U,&e->before);tuple(p+144U,&e->after);(void)memcpy(p+224U,e->descriptor_sha256,32U);(void)memcpy(p+256U,e->payload_sha256,32U);(void)memcpy(p+288U,e->delivery_sha256,32U);(void)memcpy(p+320U,e->page_sha256,32U);}*w=n;return CADR_STATUS_OK;}
