#include "cadr_m4_media.h"

#include "cadr_state_v4.h"

#include <stdlib.h>
#include <string.h>

typedef struct sha256_ctx { uint32_t h[8]; uint64_t bits; uint8_t block[64]; uint32_t used; } sha256_ctx;
typedef struct overlay_entry { uint64_t first_block; uint8_t page_sha256[CADR_SHA256_BYTES]; } overlay_entry;

static uint32_t ror32(uint32_t v,uint32_t n){return(v>>n)|(v<<(32U-n));}
static void transform(sha256_ctx*c,const uint8_t b[64]){static const uint32_t k[64]={UINT32_C(0x428a2f98),UINT32_C(0x71374491),UINT32_C(0xb5c0fbcf),UINT32_C(0xe9b5dba5),UINT32_C(0x3956c25b),UINT32_C(0x59f111f1),UINT32_C(0x923f82a4),UINT32_C(0xab1c5ed5),UINT32_C(0xd807aa98),UINT32_C(0x12835b01),UINT32_C(0x243185be),UINT32_C(0x550c7dc3),UINT32_C(0x72be5d74),UINT32_C(0x80deb1fe),UINT32_C(0x9bdc06a7),UINT32_C(0xc19bf174),UINT32_C(0xe49b69c1),UINT32_C(0xefbe4786),UINT32_C(0x0fc19dc6),UINT32_C(0x240ca1cc),UINT32_C(0x2de92c6f),UINT32_C(0x4a7484aa),UINT32_C(0x5cb0a9dc),UINT32_C(0x76f988da),UINT32_C(0x983e5152),UINT32_C(0xa831c66d),UINT32_C(0xb00327c8),UINT32_C(0xbf597fc7),UINT32_C(0xc6e00bf3),UINT32_C(0xd5a79147),UINT32_C(0x06ca6351),UINT32_C(0x14292967),UINT32_C(0x27b70a85),UINT32_C(0x2e1b2138),UINT32_C(0x4d2c6dfc),UINT32_C(0x53380d13),UINT32_C(0x650a7354),UINT32_C(0x766a0abb),UINT32_C(0x81c2c92e),UINT32_C(0x92722c85),UINT32_C(0xa2bfe8a1),UINT32_C(0xa81a664b),UINT32_C(0xc24b8b70),UINT32_C(0xc76c51a3),UINT32_C(0xd192e819),UINT32_C(0xd6990624),UINT32_C(0xf40e3585),UINT32_C(0x106aa070),UINT32_C(0x19a4c116),UINT32_C(0x1e376c08),UINT32_C(0x2748774c),UINT32_C(0x34b0bcb5),UINT32_C(0x391c0cb3),UINT32_C(0x4ed8aa4a),UINT32_C(0x5b9cca4f),UINT32_C(0x682e6ff3),UINT32_C(0x748f82ee),UINT32_C(0x78a5636f),UINT32_C(0x84c87814),UINT32_C(0x8cc70208),UINT32_C(0x90befffa),UINT32_C(0xa4506ceb),UINT32_C(0xbef9a3f7),UINT32_C(0xc67178f2)};uint32_t w[64],a,b0,d,e,f,g,h,i,j;for(i=0U;i<16U;++i){j=i*4U;w[i]=((uint32_t)b[j]<<24U)|((uint32_t)b[j+1U]<<16U)|((uint32_t)b[j+2U]<<8U)|b[j+3U];}for(i=16U;i<64U;++i)w[i]=(ror32(w[i-15U],7U)^ror32(w[i-15U],18U)^(w[i-15U]>>3U))+w[i-16U]+(ror32(w[i-2U],17U)^ror32(w[i-2U],19U)^(w[i-2U]>>10U))+w[i-7U];a=c->h[0];b0=c->h[1];d=c->h[2];e=c->h[3];f=c->h[4];g=c->h[5];h=c->h[6];j=c->h[7];for(i=0U;i<64U;++i){uint32_t t1=j+(ror32(f,6U)^ror32(f,11U)^ror32(f,25U))+((f&g)^(~f&h))+k[i]+w[i],t2=(ror32(a,2U)^ror32(a,13U)^ror32(a,22U))+((a&b0)^(a&d)^(b0&d));j=h;h=g;g=f;f=e+t1;e=d;d=b0;b0=a;a=t1+t2;}c->h[0]+=a;c->h[1]+=b0;c->h[2]+=d;c->h[3]+=e;c->h[4]+=f;c->h[5]+=g;c->h[6]+=h;c->h[7]+=j;}
static void sha_init(sha256_ctx*c){static const uint32_t h[8]={UINT32_C(0x6a09e667),UINT32_C(0xbb67ae85),UINT32_C(0x3c6ef372),UINT32_C(0xa54ff53a),UINT32_C(0x510e527f),UINT32_C(0x9b05688c),UINT32_C(0x1f83d9ab),UINT32_C(0x5be0cd19)};(void)memset(c,0,sizeof(*c));(void)memcpy(c->h,h,sizeof(h));}
static void sha_update(sha256_ctx*c,const uint8_t*p,uint64_t n){while(n!=0U){uint32_t room=64U-c->used,take=n<room?(uint32_t)n:room;(void)memcpy(c->block+c->used,p,take);c->used+=take;p+=take;n-=take;c->bits+=(uint64_t)take*8U;if(c->used==64U){transform(c,c->block);c->used=0U;}}}
static void sha_finish(sha256_ctx*c,uint8_t*out){uint32_t i;uint64_t bits=c->bits;c->block[c->used++]=UINT8_C(0x80);if(c->used>56U){while(c->used<64U)c->block[c->used++]=0U;transform(c,c->block);c->used=0U;}while(c->used<56U)c->block[c->used++]=0U;for(i=0U;i<8U;++i)c->block[56U+i]=(uint8_t)(bits>>((7U-i)*8U));transform(c,c->block);for(i=0U;i<8U;++i){out[i*4U]=(uint8_t)(c->h[i]>>24U);out[i*4U+1U]=(uint8_t)(c->h[i]>>16U);out[i*4U+2U]=(uint8_t)(c->h[i]>>8U);out[i*4U+3U]=(uint8_t)c->h[i];}}
void cadr_m4_media_sha256(const uint8_t*p,uint64_t n,uint8_t out[CADR_SHA256_BYTES]){sha256_ctx c;if(out==NULL||(n!=0U&&p==NULL))return;sha_init(&c);if(n!=0U)sha_update(&c,p,n);sha_finish(&c,out);}
static void p32(uint8_t*p,uint32_t v){p[0]=(uint8_t)v;p[1]=(uint8_t)(v>>8U);p[2]=(uint8_t)(v>>16U);p[3]=(uint8_t)(v>>24U);}static void p64(uint8_t*p,uint64_t v){uint32_t i;for(i=0U;i<8U;++i)p[i]=(uint8_t)(v>>(i*8U));}static uint32_t g32(const uint8_t*p){return(uint32_t)p[0]|((uint32_t)p[1]<<8U)|((uint32_t)p[2]<<16U)|((uint32_t)p[3]<<24U);}static uint64_t g64(const uint8_t*p){uint64_t v=0U;uint32_t i;for(i=0U;i<8U;++i)v|=(uint64_t)p[i]<<(i*8U);return v;}
static int zeros(const uint8_t*p,uint64_t n){uint64_t i;for(i=0U;i<n;++i)if(p[i]!=0U)return 0;return 1;}static int hashes_equal(const uint8_t*a,const uint8_t*b){return memcmp(a,b,CADR_SHA256_BYTES)==0;}
void cadr_m4_media_selected_base(cadr_m4_media_header*h){static const uint8_t d[32]={0xbb,0x16,0xe4,0x6a,0xd8,0x1d,0xec,0xfe,0x1e,0xfe,0x69,0x1d,0x36,0xb6,0xaa,0x4c,0xe3,0xfd,0x4f,0xfb,0x82,0x47,0x43,0x65,0xde,0x35,0x20,0x98,0x9d,0x39,0x7c,0xb5};if(h!=NULL){h->base_byte_count=CADR_M4_MEDIA_SELECTED_BASE_BYTES;(void)memcpy(h->base_sha256,d,sizeof(d));}}
static int valid_base(const cadr_m4_media_header*h){cadr_m4_media_header expected;if(h==NULL)return 0;cadr_m4_media_selected_base(&expected);return h->base_byte_count==expected.base_byte_count&&hashes_equal(h->base_sha256,expected.base_sha256);}
static void empty_hash(uint8_t d[CADR_SHA256_BYTES]){cadr_m4_media_sha256(NULL,0U,d);}static uint64_t desc_first_block(const cadr_m4_media_turn*t){return t->operation==CADR_HOST_OPERATION_BLOCK_WRITE?g64(t->descriptor+8U):g64(t->descriptor);}
static cadr_status check_descriptor(const cadr_m4_media_turn*t){uint64_t bytes;uint32_t blocks,block_bytes;uint8_t d[32],empty[32];if(t->descriptor_byte_count>64U||!zeros(t->descriptor+t->descriptor_byte_count,64U-t->descriptor_byte_count))return CADR_STATUS_INVALID_ARGUMENT;cadr_m4_media_sha256(t->descriptor,t->descriptor_byte_count,d);if(!hashes_equal(d,t->descriptor_sha256))return CADR_STATUS_INVALID_ARGUMENT;if(t->operation==CADR_HOST_OPERATION_BLOCK_READ){empty_hash(empty);if(t->descriptor_byte_count!=16U||t->request_payload_byte_count!=0U||!hashes_equal(t->request_payload_sha256,empty))return CADR_STATUS_INVALID_ARGUMENT;blocks=g32(t->descriptor+8U);block_bytes=g32(t->descriptor+12U);if(blocks==0U||block_bytes!=CADR_M4_MEDIA_PAGE_BYTES||blocks>UINT64_MAX/block_bytes)return CADR_STATUS_INVALID_ARGUMENT;bytes=(uint64_t)blocks*block_bytes;if(bytes!=t->expected_completion_byte_count||desc_first_block(t)>UINT64_MAX/block_bytes||desc_first_block(t)*block_bytes>CADR_M4_MEDIA_SELECTED_BASE_BYTES||bytes>CADR_M4_MEDIA_SELECTED_BASE_BYTES-desc_first_block(t)*block_bytes)return CADR_STATUS_INVALID_ARGUMENT;return CADR_STATUS_OK;}if(t->operation==CADR_HOST_OPERATION_BLOCK_WRITE){if(t->descriptor_byte_count!=24U||g64(t->descriptor)!=t->request_id||g64(t->descriptor+8U)!=1U||g32(t->descriptor+16U)!=1U||g32(t->descriptor+20U)!=CADR_M4_MEDIA_PAGE_BYTES||t->request_payload_byte_count!=CADR_M4_MEDIA_PAGE_BYTES||t->expected_completion_byte_count!=0U||!hashes_equal(t->request_payload_sha256,t->page_sha256))return CADR_STATUS_INVALID_ARGUMENT;return CADR_STATUS_OK;}return CADR_STATUS_INVALID_ARGUMENT;}
static void sort_entries(overlay_entry*e,uint64_t n){uint64_t i,j;for(i=1U;i<n;++i){overlay_entry v=e[i];j=i;while(j!=0U&&e[j-1U].first_block>v.first_block){e[j]=e[j-1U];--j;}e[j]=v;}}
static cadr_status root_entries(const cadr_m4_media_header*h,const overlay_entry*e,uint64_t n,uint8_t root[32]){static const uint8_t domain[]={ 'C','D','R','M','4','O','V','E','R','L','A','Y','1',0U };uint8_t*buf;uint64_t bytes,i;if(h==NULL||root==NULL||!valid_base(h)||n>(UINT64_MAX-(uint64_t)sizeof(domain)-32U-8U)/40U||n>(uint64_t)SIZE_MAX/40U)return CADR_STATUS_INVALID_ARGUMENT;bytes=(uint64_t)sizeof(domain)+32U+8U+n*40U;buf=malloc((size_t)bytes);if(buf==NULL)return CADR_STATUS_NO_MEMORY;(void)memcpy(buf,domain,sizeof(domain));(void)memcpy(buf+sizeof(domain),h->base_sha256,32U);p64(buf+sizeof(domain)+32U,n);for(i=0U;i<n;++i){p64(buf+sizeof(domain)+40U+i*40U,e[i].first_block);(void)memcpy(buf+sizeof(domain)+48U+i*40U,e[i].page_sha256,32U);}cadr_m4_media_sha256(buf,bytes,root);free(buf);return CADR_STATUS_OK;}
cadr_status cadr_m4_media_overlay_root(const cadr_m4_media_header*h,const cadr_m4_media_turn*t,uint64_t count,uint8_t root[32]){overlay_entry*e;uint64_t n=0U,i,j; cadr_status s;if(!valid_base(h)||root==NULL||(count!=0U&&t==NULL)||count>(uint64_t)SIZE_MAX/sizeof(*e))return CADR_STATUS_INVALID_ARGUMENT;e=count==0U?NULL:calloc((size_t)count,sizeof(*e));if(count!=0U&&e==NULL)return CADR_STATUS_NO_MEMORY;for(i=0U;i<count;++i)if(t[i].actor==CADR_M4_MEDIA_ACTOR_DELIVERY&&t[i].operation==CADR_HOST_OPERATION_BLOCK_WRITE&&t[i].disposition==CADR_M4_MEDIA_DISPOSITION_COMMIT){for(j=0U;j<n&&e[j].first_block!=desc_first_block(&t[i]);++j){}if(j==n){e[n].first_block=desc_first_block(&t[i]);n++;}(void)memcpy(e[j].page_sha256,t[i].page_sha256,32U);}sort_entries(e,n);s=root_entries(h,e,n,root);free(e);return s;}
static int same_request(const cadr_m4_media_turn *a,const cadr_m4_media_turn *b){return a->operation==b->operation&&a->generation==b->generation&&a->request_id==b->request_id&&a->descriptor_byte_count==b->descriptor_byte_count&&a->request_payload_byte_count==b->request_payload_byte_count&&a->expected_completion_byte_count==b->expected_completion_byte_count&&memcmp(a->descriptor,b->descriptor,64U)==0&&hashes_equal(a->descriptor_sha256,b->descriptor_sha256)&&hashes_equal(a->request_payload_sha256,b->request_payload_sha256);}
static cadr_status validate_chain(const cadr_m4_media_header*h,const cadr_m4_media_turn*t,uint64_t n)
{
    uint64_t i, expect=CADR_M4_MEDIA_ACTOR_ISSUE, last_tick=0U, overlay=0U, begin=0U;
    uint8_t empty[32],root[32],before[32],post[32]; cadr_status s;
    if(!valid_base(h)||n==0U)return CADR_STATUS_INVALID_ARGUMENT;
    empty_hash(empty); s=cadr_m4_media_overlay_root(h,t,0U,root); if(s!=CADR_STATUS_OK)return s;
    for(i=0U;i<n;++i){const cadr_m4_media_turn*x=&t[i];
        if(x->ordinal!=i||x->actor!=expect||(i!=0U&&x->guest_tick<last_tick))return CADR_STATUS_INVALID_ARGUMENT;
        last_tick=x->guest_tick;
        if(x->actor==CADR_M4_MEDIA_ACTOR_STABLE){
            if(i+1U!=n||x->disposition!=0U||x->operation!=0U||x->actor_status!=CADR_STATUS_OK||x->generation!=0U||x->request_id!=0U||x->descriptor_byte_count!=0U||x->request_payload_byte_count!=0U||x->expected_completion_byte_count!=0U||x->delivered_completion_byte_count!=0U||!zeros(x->descriptor,64U)||!hashes_equal(x->descriptor_sha256,empty)||!hashes_equal(x->request_payload_sha256,empty)||!hashes_equal(x->page_sha256,empty)||!hashes_equal(x->overlay_root_sha256,root)||x->overlay_generation!=overlay||hashes_equal(x->stabilized_state_sha256,empty))return CADR_STATUS_INVALID_ARGUMENT;
            return CADR_STATUS_OK;
        }
        if(x->generation==0U||x->request_id==0U||!zeros(x->stabilized_state_sha256,32U)||(s=check_descriptor(x))!=CADR_STATUS_OK)return s;
        if(x->actor==CADR_M4_MEDIA_ACTOR_ISSUE){begin=i;if(x->actor_status!=CADR_STATUS_OK||x->disposition!=0U||x->delivered_completion_byte_count!=0U||x->overlay_generation!=overlay||!hashes_equal(x->overlay_root_sha256,root))return CADR_STATUS_INVALID_ARGUMENT; if(x->operation==CADR_HOST_OPERATION_BLOCK_READ&&!hashes_equal(x->page_sha256,empty))return CADR_STATUS_INVALID_ARGUMENT; expect=CADR_M4_MEDIA_ACTOR_CAPTURE;continue;}
        if(!same_request(x,&t[begin]))return CADR_STATUS_INVALID_ARGUMENT;
        (void)memcpy(before,root,32U);
        if(x->actor==CADR_M4_MEDIA_ACTOR_CAPTURE){if(x->actor_status!=CADR_STATUS_OK||x->disposition!=0U||x->delivered_completion_byte_count!=0U||x->overlay_generation!=overlay||!hashes_equal(x->overlay_root_sha256,before)||!hashes_equal(x->page_sha256,t[begin].page_sha256))return CADR_STATUS_INVALID_ARGUMENT;expect=CADR_M4_MEDIA_ACTOR_DELIVERY;continue;}
        if(x->actor==CADR_M4_MEDIA_ACTOR_DELIVERY){
            if(x->actor_status!=CADR_HOST_RESULT_OK&&x->actor_status!=CADR_HOST_RESULT_FAILED)return CADR_STATUS_INVALID_ARGUMENT;
            if(x->delivered_completion_byte_count!=x->expected_completion_byte_count)return CADR_STATUS_INVALID_ARGUMENT;
            if(x->operation==CADR_HOST_OPERATION_BLOCK_WRITE&&!hashes_equal(x->page_sha256,x->request_payload_sha256))return CADR_STATUS_INVALID_ARGUMENT;
            if(x->actor_status==CADR_HOST_RESULT_OK){if(x->operation==CADR_HOST_OPERATION_BLOCK_WRITE){if(x->disposition!=CADR_M4_MEDIA_DISPOSITION_COMMIT||overlay==UINT64_MAX)return CADR_STATUS_INVALID_ARGUMENT;overlay++;s=cadr_m4_media_overlay_root(h,t,i+1U,post);if(s!=CADR_STATUS_OK)return s;(void)memcpy(root,post,32U);}else if(x->disposition!=0U)return CADR_STATUS_INVALID_ARGUMENT;}else if(x->disposition!=CADR_M4_MEDIA_DISPOSITION_ABORT)return CADR_STATUS_INVALID_ARGUMENT;
            if(x->overlay_generation!=overlay||!hashes_equal(x->overlay_root_sha256,root))return CADR_STATUS_INVALID_ARGUMENT;
            expect=CADR_M4_MEDIA_ACTOR_APPLY;continue;
        }
        if(x->actor_status!=CADR_STATUS_OK||x->delivered_completion_byte_count!=x->expected_completion_byte_count||x->disposition!=t[i-1U].disposition||x->overlay_generation!=overlay||!hashes_equal(x->overlay_root_sha256,root)||!hashes_equal(x->page_sha256,t[i-1U].page_sha256))return CADR_STATUS_INVALID_ARGUMENT;
        expect=(i+1U<n&&t[i+1U].actor==CADR_M4_MEDIA_ACTOR_ISSUE)?CADR_M4_MEDIA_ACTOR_ISSUE:CADR_M4_MEDIA_ACTOR_STABLE;
    }
    return CADR_STATUS_INVALID_ARGUMENT;
}
cadr_status cadr_m4_media_build_stable_turn(const cadr_machine_state*s,uint64_t ordinal,uint64_t tick,uint64_t overlay,const uint8_t root[32],cadr_m4_media_turn*t){uint8_t empty[32];if(s==NULL||root==NULL||t==NULL||s->events.outstanding_request_id!=0U||s->events.completion_queued!=0U||s->events.request_descriptor_byte_count!=0U||s->events.request_payload_byte_count!=0U||s->events.expected_completion_byte_count!=0U||s->events.completion_byte_count!=0U||s->events.completion_bytes!=NULL||s->events.outstanding_operation!=CADR_HOST_OPERATION_NONE)return CADR_STATUS_NOT_READY;(void)memset(t,0,sizeof(*t));empty_hash(empty);t->ordinal=ordinal;t->actor=CADR_M4_MEDIA_ACTOR_STABLE;t->actor_status=CADR_STATUS_OK;t->guest_tick=tick;t->overlay_generation=overlay;(void)memcpy(t->descriptor_sha256,empty,32U);(void)memcpy(t->request_payload_sha256,empty,32U);(void)memcpy(t->page_sha256,empty,32U);(void)memcpy(t->overlay_root_sha256,root,32U);return cadr_state_v4_digest(s,t->stabilized_state_sha256);}
cadr_status cadr_m4_media_serialized_size(uint64_t n,uint64_t*out){if(out==NULL)return CADR_STATUS_INVALID_ARGUMENT;if(n>(UINT64_MAX-CADR_M4_MEDIA_HEADER_BYTES)/CADR_M4_MEDIA_TURN_BYTES)return CADR_STATUS_WRONG_LENGTH;*out=CADR_M4_MEDIA_HEADER_BYTES+n*CADR_M4_MEDIA_TURN_BYTES;return CADR_STATUS_OK;}
static void encode_turn(uint8_t*p,const cadr_m4_media_turn*t){(void)memset(p,0,352U);p64(p,t->ordinal);p32(p+8U,t->actor);p32(p+12U,t->disposition);p32(p+16U,t->operation);p32(p+20U,t->actor_status);p64(p+24U,t->guest_tick);p64(p+32U,t->generation);p64(p+40U,t->request_id);p64(p+48U,t->descriptor_byte_count);p64(p+56U,t->request_payload_byte_count);p64(p+64U,t->expected_completion_byte_count);p64(p+72U,t->delivered_completion_byte_count);(void)memcpy(p+80U,t->descriptor,64U);(void)memcpy(p+144U,t->descriptor_sha256,32U);(void)memcpy(p+176U,t->request_payload_sha256,32U);(void)memcpy(p+208U,t->page_sha256,32U);p64(p+240U,t->overlay_generation);(void)memcpy(p+248U,t->overlay_root_sha256,32U);(void)memcpy(p+280U,t->stabilized_state_sha256,32U);}
static void decode_turn(const uint8_t*p,cadr_m4_media_turn*t){(void)memset(t,0,sizeof(*t));t->ordinal=g64(p);t->actor=g32(p+8U);t->disposition=g32(p+12U);t->operation=g32(p+16U);t->actor_status=g32(p+20U);t->guest_tick=g64(p+24U);t->generation=g64(p+32U);t->request_id=g64(p+40U);t->descriptor_byte_count=g64(p+48U);t->request_payload_byte_count=g64(p+56U);t->expected_completion_byte_count=g64(p+64U);t->delivered_completion_byte_count=g64(p+72U);(void)memcpy(t->descriptor,p+80U,64U);(void)memcpy(t->descriptor_sha256,p+144U,32U);(void)memcpy(t->request_payload_sha256,p+176U,32U);(void)memcpy(t->page_sha256,p+208U,32U);t->overlay_generation=g64(p+240U);(void)memcpy(t->overlay_root_sha256,p+248U,32U);(void)memcpy(t->stabilized_state_sha256,p+280U,32U);}
static cadr_status decode_validate(const uint8_t*b,uint64_t count,cadr_m4_media_header*h,cadr_m4_media_turn**out,uint64_t*n){uint64_t i; cadr_m4_media_turn*t;cadr_status s;if(b==NULL||h==NULL||out==NULL||n==NULL||count<CADR_M4_MEDIA_HEADER_BYTES||(count-CADR_M4_MEDIA_HEADER_BYTES)%CADR_M4_MEDIA_TURN_BYTES!=0U)return CADR_STATUS_INVALID_ARGUMENT;if(memcmp(b,"CDRM4MEDIA1",11U)!=0||b[11U]!=0U||g32(b+12U)!=1U||!zeros(b+56U,8U))return CADR_STATUS_PROFILE_MISMATCH;h->base_byte_count=g64(b+16U);(void)memcpy(h->base_sha256,b+24U,32U);*n=(count-64U)/352U;if(!valid_base(h)||*n>(uint64_t)SIZE_MAX/sizeof(*t))return CADR_STATUS_INVALID_ARGUMENT;t=calloc((size_t)*n,sizeof(*t));if(t==NULL)return CADR_STATUS_NO_MEMORY;for(i=0U;i<*n;++i){const uint8_t*p=b+64U+i*352U;if(!zeros(p+312U,40U)){free(t);return CADR_STATUS_INVALID_ARGUMENT;}decode_turn(p,&t[i]);}s=validate_chain(h,t,*n);if(s!=CADR_STATUS_OK){free(t);return s;}*out=t;return CADR_STATUS_OK;}
cadr_status cadr_m4_media_serialize(const cadr_m4_media_header*h,const cadr_m4_media_turn*t,uint64_t n,uint8_t*b,uint64_t cap,uint64_t*written){uint64_t need,i;cadr_status s;if(written!=NULL)*written=0U;if(h==NULL||t==NULL||b==NULL||written==NULL)return CADR_STATUS_INVALID_ARGUMENT;if((s=cadr_m4_media_serialized_size(n,&need))!=CADR_STATUS_OK)return s;if(cap<need)return CADR_STATUS_WRONG_LENGTH;if((s=validate_chain(h,t,n))!=CADR_STATUS_OK)return s;(void)memset(b,0,(size_t)need);(void)memcpy(b,"CDRM4MEDIA1",11U);p32(b+12U,1U);p64(b+16U,h->base_byte_count);(void)memcpy(b+24U,h->base_sha256,32U);for(i=0U;i<n;++i)encode_turn(b+64U+i*352U,&t[i]);*written=need;return CADR_STATUS_OK;}
cadr_status cadr_m4_media_compare(const uint8_t*l,uint64_t lc,const uint8_t*r,uint64_t rc,cadr_m4_media_difference*d){cadr_m4_media_header lh,rh;cadr_m4_media_turn*lt,*rt;uint64_t ln,rn,i,limit;cadr_status s;if(d==NULL)return CADR_STATUS_INVALID_ARGUMENT;s=decode_validate(l,lc,&lh,&lt,&ln);if(s!=CADR_STATUS_OK)return s;s=decode_validate(r,rc,&rh,&rt,&rn);if(s!=CADR_STATUS_OK){free(lt);return s;}limit=lc<rc?lc:rc;for(i=0U;i<limit;++i)if(l[i]!=r[i]){d->turn_ordinal=i<64U?UINT64_MAX:(i-64U)/352U;d->byte_offset=i;d->left_byte=l[i];d->right_byte=r[i];free(lt);free(rt);return CADR_STATUS_ARTIFACT_MISMATCH;}if(lc!=rc){d->turn_ordinal=limit<64U?UINT64_MAX:(limit-64U)/352U;d->byte_offset=limit;d->left_byte=lc>limit?l[limit]:0U;d->right_byte=rc>limit?r[limit]:0U;free(lt);free(rt);return CADR_STATUS_ARTIFACT_MISMATCH;}free(lt);free(rt);(void)lh;(void)rh;(void)ln;(void)rn;return CADR_STATUS_OK;}
